-- Generated to match src/offsite/fixtures.
-- Safe to re-run: clears the lts-2026 events slate first, then reinserts.
-- Thursday is one approved event per source; Friday stays denser.

-- RSVPs reference events, so clear those first.
delete from rsvps
where event_id in (select id from events where conference_id = 'lts-2026');

delete from events where conference_id = 'lts-2026';

update conferences
set nights = array['2026-07-30','2026-07-31']::text[]
where id = 'lts-2026';

insert into events (id, conference_id, source, source_event_id, source_url, title, description, starts_at, ends_at, venue_name, lat, lng, tags, external_going_count, is_official, curation_status, curation_rationale, submitted_by) values
  ('official:lts-opening-reception', 'lts-2026', 'official', 'lts-opening-reception', '#', 'Summit Opening Reception', 'Drinks and small plates on the terrace. Badge required.', '2026-07-30T18:00:00-05:00'::timestamptz, '2026-07-30T21:00:00-05:00'::timestamptz, 'Austin Convention Center - Terrace', 30.2637, -97.7397, ARRAY['AI','FinTech','DevTools','Design','Climate']::text[], NULL, true, 'approved', 'matches AI, FinTech, DevTools, Design, Climate · 0.0 mi from venue', NULL),
  ('official:lts-closing-party', 'lts-2026', 'official', 'lts-closing-party', '#', 'Closing Party', 'Rainey Street. Live music, tacos, and the last chance to swap numbers.', '2026-07-31T20:00:00-05:00'::timestamptz, '2026-07-31T23:59:00-05:00'::timestamptz, 'Banger''s', 30.2551, -97.7379, ARRAY['AI','FinTech','DevTools','Design','Climate']::text[], NULL, true, 'approved', 'matches AI, FinTech, DevTools, Design, Climate · 0.6 mi from venue', NULL),
  ('eventbrite:eb-startup-crawl', 'lts-2026', 'eventbrite', 'eb-startup-crawl', 'https://www.eventbrite.com/e/austin-startup-crawl', 'Austin Startup Crawl', 'Forty companies, one warehouse, free beer. The classic Austin scramble.', '2026-07-30T18:30:00-05:00'::timestamptz, '2026-07-30T22:00:00-05:00'::timestamptz, 'Native Hostel', 30.2688, -97.7263, ARRAY['DevTools','AI']::text[], 900, false, 'approved', 'matches DevTools, AI · 0.9 mi from venue', NULL),
  ('eventbrite:eb-barton-springs', 'lts-2026', 'eventbrite', 'eb-barton-springs', 'https://www.eventbrite.com/e/barton-springs-sunset', 'Barton Springs Sunset Swim', 'Sixty-eight degrees year round. Bring a towel.', '2026-07-31T18:30:00-05:00'::timestamptz, '2026-07-31T20:00:00-05:00'::timestamptz, 'Barton Springs Pool', 30.264, -97.7713, ARRAY['Climate']::text[], 180, false, 'approved', 'matches Climate · 1.9 mi from venue', NULL),
  ('eventbrite:eb-two-step-lessons', 'lts-2026', 'eventbrite', 'eb-two-step-lessons', 'https://www.eventbrite.com/e/white-horse-two-step', 'Two-Step Lessons at the White Horse', 'Free lesson at 7, band at 8, no experience and no partner needed.', '2026-07-31T19:00:00-05:00'::timestamptz, '2026-07-31T23:00:00-05:00'::timestamptz, 'The White Horse', 30.2637, -97.7169, ARRAY[]::text[], 260, false, 'approved', 'no tag match · 1.4 mi from venue', NULL),
  ('partiful:ptf-design-systems-dinner', 'lts-2026', 'partiful', 'ptf-design-systems-dinner', 'https://partiful.com/e/design-systems-dinner', 'Design Systems Dinner', 'Small dinner for people who argue about tokens for a living.', '2026-07-30T19:30:00-05:00'::timestamptz, '2026-07-30T22:30:00-05:00'::timestamptz, 'Comedor', 30.267, -97.7462, ARRAY['Design']::text[], 22, false, 'approved', 'matches Design · 0.4 mi from venue', NULL),
  ('luma:luma-fintech-after-hours', 'lts-2026', 'luma', 'luma-fintech-after-hours', 'https://lu.ma/fintech-after-hours', 'FinTech After Hours', 'Rainey Street patio takeover. Payments, ledgers, and frozen margaritas.', '2026-07-30T18:00:00-05:00'::timestamptz, '2026-07-30T21:00:00-05:00'::timestamptz, 'Half Step', 30.2549, -97.7383, ARRAY['FinTech']::text[], 95, false, 'approved', 'matches FinTech · 0.6 mi from venue', NULL),
  ('shotgun:sg-sunset-boat-party', 'lts-2026', 'shotgun', 'sg-sunset-boat-party', 'https://shotgun.live/events/lady-bird-sunset-boat-party', 'Lady Bird Sunset Boat Party', 'Two hours on the water with a house set. Boards at 6 sharp, capped at 120.', '2026-07-30T18:00:00-05:00'::timestamptz, '2026-07-30T21:00:00-05:00'::timestamptz, 'Hyatt Boat Dock', 30.2604, -97.7513, ARRAY[]::text[], 410, false, 'approved', 'no tag match · 0.7 mi from venue', NULL),
  ('partiful:ptf-ai-founders-dinner', 'lts-2026', 'partiful', 'ptf-ai-founders-dinner', 'https://partiful.com/e/ai-founders-dinner', 'AI Founders Dinner', 'Long table, no name tags, no pitches. 20 seats, first come.', '2026-07-31T19:00:00-05:00'::timestamptz, '2026-07-31T22:00:00-05:00'::timestamptz, 'Emmer & Rye', 30.2597, -97.7395, ARRAY['AI']::text[], 14, false, 'approved', 'matches AI · 0.3 mi from venue', NULL),
  ('luma:luma-devtools-hh', 'lts-2026', 'luma', 'luma-devtools-hh', 'https://lu.ma/devtools-austin', 'DevTools Happy Hour', 'Open bar for the first hour. Hosted by the Austin DevTools collective.', '2026-07-31T17:30:00-05:00'::timestamptz, '2026-07-31T20:00:00-05:00'::timestamptz, 'Capital Factory', 30.2686, -97.7409, ARRAY['DevTools']::text[], 120, false, 'approved', 'matches DevTools · 0.3 mi from venue', NULL),
  ('partiful:ptf-climate-nightcap', 'lts-2026', 'partiful', 'ptf-climate-nightcap', 'https://partiful.com/e/climate-nightcap', 'Climate Tech Nightcap', 'Last-night drinks for the climate crowd. Bring someone you just met.', '2026-07-31T21:00:00-05:00'::timestamptz, '2026-07-31T23:59:00-05:00'::timestamptz, 'Kitty Cohen''s', 30.2649, -97.7213, ARRAY['Climate']::text[], 38, false, 'approved', 'matches Climate · 1.1 mi from venue', NULL),
  ('luma:luma-ai-infra-meetup', 'lts-2026', 'luma', 'luma-ai-infra-meetup', 'https://lu.ma/ai-infra-atx', 'AI Infra Meetup', 'Three lightning talks on inference cost, then everyone goes to the patio.', '2026-07-31T18:00:00-05:00'::timestamptz, '2026-07-31T20:30:00-05:00'::timestamptz, 'Capital Factory', 30.2686, -97.7409, ARRAY['AI','DevTools']::text[], 160, false, 'approved', 'matches AI, DevTools · 0.3 mi from venue', NULL),
  ('shotgun:sg-rooftop-social', 'lts-2026', 'shotgun', 'sg-rooftop-social', 'https://shotgun.live/events/rainey-rooftop-social', 'Rainey Rooftop Social', 'Rooftop, skyline view, no cover before 9. Easy first stop.', '2026-07-31T20:00:00-05:00'::timestamptz, '2026-07-31T23:30:00-05:00'::timestamptz, 'The Bungalow Rooftop', 30.2557, -97.7392, ARRAY['Design']::text[], 430, false, 'approved', 'matches Design · 0.6 mi from venue', NULL),
  ('shotgun:sg-summit-rooftop-dj', 'lts-2026', 'shotgun', 'sg-summit-rooftop-dj', 'https://shotgun.live/events/summit-rooftop-dj-set', 'Rooftop DJ Set - Closing Night', 'Open-air decks over Congress. Sunset slot, then house until 1.', '2026-07-31T21:00:00-05:00'::timestamptz, '2026-08-01T01:00:00-05:00'::timestamptz, 'Upstairs at Caroline', 30.2668, -97.7423, ARRAY[]::text[], 630, false, 'approved', 'no tag match · 0.3 mi from venue', NULL),
  ('shotgun:sg-barbarella-throwback', 'lts-2026', 'shotgun', 'sg-barbarella-throwback', 'https://shotgun.live/events/barbarella-throwback', 'Barbarella Throwback Friday', 'Nothing after 2009. Two rooms, no cover with a summit badge before 11.', '2026-07-31T22:00:00-05:00'::timestamptz, '2026-08-01T02:00:00-05:00'::timestamptz, 'Barbarella', 30.2676, -97.7357, ARRAY[]::text[], 520, false, 'approved', 'no tag match · 0.4 mi from venue', NULL),
  ('shotgun:sg-open-air-block-party', 'lts-2026', 'shotgun', 'sg-open-air-block-party', 'https://shotgun.live/events/east-austin-open-air', 'Open Air: East Austin Block Party', 'Outdoor stage, food trucks, all-local lineup. Runs straight through.', '2026-07-31T20:00:00-05:00'::timestamptz, '2026-08-01T01:00:00-05:00'::timestamptz, 'Springdale Yard', 30.264, -97.716, ARRAY[]::text[], 1180, false, 'approved', 'no tag match · 1.4 mi from venue', NULL),
  ('partiful:ptf-wine-on-second', 'lts-2026', 'partiful', 'ptf-wine-on-second', 'https://partiful.com/e/wine-on-second', 'Wine on Second', 'Low-key patio wine, no pitching. Bring one person you met today.', '2026-07-31T18:00:00-05:00'::timestamptz, '2026-07-31T21:00:00-05:00'::timestamptz, 'June''s All Day', 30.2503, -97.7511, ARRAY[]::text[], 19, false, 'approved', 'no tag match · 1.1 mi from venue', NULL),
  ('partiful:ptf-zilker-picnic', 'lts-2026', 'partiful', 'ptf-zilker-picnic', 'https://partiful.com/e/zilker-sunset-picnic', 'Zilker Sunset Picnic', 'Blankets on the great lawn. Bring something to share, leave nothing behind.', '2026-07-31T19:00:00-05:00'::timestamptz, '2026-07-31T21:00:00-05:00'::timestamptz, 'Zilker Park', 30.2669, -97.7729, ARRAY['Climate']::text[], 41, false, 'approved', 'matches Climate · 2.0 mi from venue', NULL),
  ('partiful:ptf-late-night-pizza', 'lts-2026', 'partiful', 'ptf-late-night-pizza', 'https://partiful.com/e/late-night-pizza-council', 'Late Night Pizza Council', 'The last stop, every year. Slices on the sidewalk until they kick us out.', '2026-07-31T23:00:00-05:00'::timestamptz, '2026-08-01T01:30:00-05:00'::timestamptz, 'Home Slice Pizza', 30.25, -97.743, ARRAY[]::text[], 60, false, 'approved', 'no tag match · 1.0 mi from venue', NULL),
  ('luma:luma-stripe-payments-eng', 'lts-2026', 'luma', 'luma-stripe-payments-eng', 'https://lu.ma/payments-engineering-atx', 'Payments Engineering w/ Stripe', 'Idempotency, ledgers, and the failure modes nobody writes blog posts about.', '2026-07-31T17:30:00-05:00'::timestamptz, '2026-07-31T20:00:00-05:00'::timestamptz, 'Stripe Austin', 30.2648, -97.7476, ARRAY['FinTech','DevTools']::text[], 130, false, 'approved', 'matches FinTech, DevTools · 0.5 mi from venue', NULL),
  ('luma:luma-nvidia-inference', 'lts-2026', 'luma', 'luma-nvidia-inference', 'https://lu.ma/inference-at-scale-atx', 'Inference at Scale - NVIDIA', 'Batching, quantisation, and what actually moves cost per token.', '2026-07-31T17:00:00-05:00'::timestamptz, '2026-07-31T19:30:00-05:00'::timestamptz, 'Capital Factory', 30.2686, -97.7409, ARRAY['AI']::text[], 185, false, 'approved', 'matches AI · 0.3 mi from venue', NULL),
  ('luma:luma-datadog-observability', 'lts-2026', 'luma', 'luma-datadog-observability', 'https://lu.ma/observability-night-atx', 'Observability Night - Datadog', 'Traces over dashboards. War stories from three on-call rotations.', '2026-07-31T18:00:00-05:00'::timestamptz, '2026-07-31T20:30:00-05:00'::timestamptz, 'Austin Central Library', 30.2668, -97.75, ARRAY['DevTools']::text[], 88, false, 'approved', 'matches DevTools · 0.7 mi from venue', NULL),
  ('luma:luma-github-open-source', 'lts-2026', 'luma', 'luma-github-open-source', 'https://lu.ma/open-source-night-atx', 'Open Source Night - GitHub', 'Maintainers on burnout, funding, and saying no. Then a patio.', '2026-07-31T18:30:00-05:00'::timestamptz, '2026-07-31T21:00:00-05:00'::timestamptz, 'Central Machine Works', 30.2652, -97.7152, ARRAY['DevTools']::text[], 150, false, 'approved', 'matches DevTools · 1.5 mi from venue', NULL),
  ('attendee:host-cto-fireside', 'lts-2026', 'attendee', 'host-cto-fireside', '', 'CTO Fireside: Shipping AI in Production', 'Off the record, no slides. What actually broke when we put models in front of customers — and what we would do differently. Thirty seats.', '2026-07-30T18:00:00-05:00'::timestamptz, '2026-07-30T20:30:00-05:00'::timestamptz, 'The Roosevelt Room', 30.2683, -97.7477, ARRAY['AI','DevTools']::text[], NULL, false, 'approved', 'Hosted by an attendee · approved by the organizer', 'a2'),
  ('attendee:host-tech-meetup-hh', 'lts-2026', 'attendee', 'host-tech-meetup-hh', '', 'Tech Meetup Happy Hour', 'The engineering side of the summit, on a patio, before the parties start. Interns very much included.', '2026-07-31T17:30:00-05:00'::timestamptz, '2026-07-31T20:00:00-05:00'::timestamptz, 'Easy Tiger', 30.2679, -97.7392, ARRAY['DevTools','AI']::text[], NULL, false, 'approved', 'Hosted by an attendee · approved by the organizer', 'a6'),
  ('attendee:sub-boardgames', 'lts-2026', 'attendee', 'sub-boardgames', '', 'Board games + beer', 'Grabbing the back room at Emerald Tavern. Bringing Wingspan and Azul, all welcome.', '2026-07-30T20:00:00-05:00'::timestamptz, '2026-07-30T23:00:00-05:00'::timestamptz, 'Emerald Tavern Games & Cafe', 30.2711, -97.7437, ARRAY['DevTools']::text[], NULL, false, 'candidate', 'Submitted by an attendee', 'a2'),
  ('attendee:sub-morningrun', 'lts-2026', 'attendee', 'sub-morningrun', '', 'Sunrise run along the trail', 'Easy 3 miles before the keynote. Meeting at the boardwalk entrance.', '2026-07-31T06:30:00-05:00'::timestamptz, '2026-07-31T07:30:00-05:00'::timestamptz, 'Ann and Roy Butler Trail', 30.2523, -97.7411, ARRAY[]::text[], NULL, false, 'candidate', 'Submitted by an attendee', 'a47'),
  ('eventbrite:eb-5k', 'lts-2026', 'eventbrite', 'eb-5k', 'https://www.eventbrite.com/e/lady-bird-5k', 'Lady Bird Lake 5K', 'Charity fun run around the trail.', '2026-07-30T07:00:00-05:00'::timestamptz, '2026-07-30T09:00:00-05:00'::timestamptz, 'Auditorium Shores', 30.2622, -97.7515, ARRAY[]::text[], 340, false, 'rejected', 'no tag match · morning slot · not a networking context', NULL);

insert into rsvps (event_id, attendee_id, anonymous) values
  ('official:lts-opening-reception', 'a2', false), ('official:lts-opening-reception', 'a3', false), ('official:lts-opening-reception', 'a4', false), ('official:lts-opening-reception', 'a5', false), ('official:lts-opening-reception', 'a6', false), ('official:lts-opening-reception', 'a8', false), ('official:lts-opening-reception', 'a14', false), ('official:lts-opening-reception', 'a16', false), ('official:lts-opening-reception', 'a20', false), ('official:lts-opening-reception', 'a39', false), ('official:lts-opening-reception', 'a45', false), ('official:lts-opening-reception', 'a54', false), ('official:lts-opening-reception', 'a57', false), ('official:lts-opening-reception', 'a61', false), ('official:lts-opening-reception', 'a9', true),
  ('official:lts-closing-party', 'a2', false), ('official:lts-closing-party', 'a3', false), ('official:lts-closing-party', 'a4', false), ('official:lts-closing-party', 'a6', false), ('official:lts-closing-party', 'a8', false), ('official:lts-closing-party', 'a12', false), ('official:lts-closing-party', 'a19', false), ('official:lts-closing-party', 'a39', false), ('official:lts-closing-party', 'a45', false), ('official:lts-closing-party', 'a57', false), ('official:lts-closing-party', 'a61', false), ('official:lts-closing-party', 'a63', false), ('official:lts-closing-party', 'a9', true), ('official:lts-closing-party', 'a13', true),
  ('eventbrite:eb-startup-crawl', 'a2', false), ('eventbrite:eb-startup-crawl', 'a39', false), ('eventbrite:eb-startup-crawl', 'a15', false),
  ('partiful:ptf-design-systems-dinner', 'a3', false), ('partiful:ptf-design-systems-dinner', 'a19', false), ('partiful:ptf-design-systems-dinner', 'a57', false), ('partiful:ptf-design-systems-dinner', 'a61', false), ('partiful:ptf-design-systems-dinner', 'a12', false),
  ('luma:luma-fintech-after-hours', 'a5', false), ('luma:luma-fintech-after-hours', 'a8', false), ('luma:luma-fintech-after-hours', 'a14', false), ('luma:luma-fintech-after-hours', 'a20', false), ('luma:luma-fintech-after-hours', 'a23', false), ('luma:luma-fintech-after-hours', 'a39', false),
  ('shotgun:sg-sunset-boat-party', 'a3', false), ('shotgun:sg-sunset-boat-party', 'a19', false), ('shotgun:sg-sunset-boat-party', 'a22', false), ('shotgun:sg-sunset-boat-party', 'a26', false), ('shotgun:sg-sunset-boat-party', 'a31', false), ('shotgun:sg-sunset-boat-party', 'a57', false), ('shotgun:sg-sunset-boat-party', 'a61', false), ('shotgun:sg-sunset-boat-party', 'a56', false), ('shotgun:sg-sunset-boat-party', 'a12', false), ('shotgun:sg-sunset-boat-party', 'a10', false), ('shotgun:sg-sunset-boat-party', 'a24', false), ('shotgun:sg-sunset-boat-party', 'a30', false), ('shotgun:sg-sunset-boat-party', 'a42', false), ('shotgun:sg-sunset-boat-party', 'a44', false), ('shotgun:sg-sunset-boat-party', 'a11', true),
  ('attendee:host-cto-fireside', 'a2', false), ('attendee:host-cto-fireside', 'a6', false), ('attendee:host-cto-fireside', 'a16', false), ('attendee:host-cto-fireside', 'a45', false), ('attendee:host-cto-fireside', 'a46', false), ('attendee:host-cto-fireside', 'a50', false), ('attendee:host-cto-fireside', 'a51', false), ('attendee:host-cto-fireside', 'a52', false), ('attendee:host-cto-fireside', 'a53', false), ('attendee:host-cto-fireside', 'a54', false), ('attendee:host-cto-fireside', 'a58', false), ('attendee:host-cto-fireside', 'a60', false), ('attendee:host-cto-fireside', 'a62', false), ('attendee:host-cto-fireside', 'a63', false), ('attendee:host-cto-fireside', 'a48', false), ('attendee:host-cto-fireside', 'a49', false), ('attendee:host-cto-fireside', 'a55', false), ('attendee:host-cto-fireside', 'a59', false), ('attendee:host-cto-fireside', 'a39', false), ('attendee:host-cto-fireside', 'a1', false), ('attendee:host-cto-fireside', 'a18', true),
  ('partiful:ptf-ai-founders-dinner', 'a2', false), ('partiful:ptf-ai-founders-dinner', 'a45', false), ('partiful:ptf-ai-founders-dinner', 'a50', false), ('partiful:ptf-ai-founders-dinner', 'a52', false), ('partiful:ptf-ai-founders-dinner', 'a54', false), ('partiful:ptf-ai-founders-dinner', 'a58', false), ('partiful:ptf-ai-founders-dinner', 'a16', true),
  ('luma:luma-devtools-hh', 'a2', false), ('luma:luma-devtools-hh', 'a6', false), ('luma:luma-devtools-hh', 'a15', false), ('luma:luma-devtools-hh', 'a16', false), ('luma:luma-devtools-hh', 'a46', false), ('luma:luma-devtools-hh', 'a59', false),
  ('luma:luma-ai-infra-meetup', 'a2', false), ('luma:luma-ai-infra-meetup', 'a45', false), ('luma:luma-ai-infra-meetup', 'a50', false), ('luma:luma-ai-infra-meetup', 'a54', false), ('luma:luma-ai-infra-meetup', 'a60', false),
  ('partiful:ptf-climate-nightcap', 'a19', false), ('partiful:ptf-climate-nightcap', 'a8', false),
  ('eventbrite:eb-barton-springs', 'a19', false), ('eventbrite:eb-barton-springs', 'a61', false),
  ('eventbrite:eb-two-step-lessons', 'a19', false), ('eventbrite:eb-two-step-lessons', 'a21', false), ('eventbrite:eb-two-step-lessons', 'a25', false), ('eventbrite:eb-two-step-lessons', 'a29', false), ('eventbrite:eb-two-step-lessons', 'a33', false), ('eventbrite:eb-two-step-lessons', 'a35', false), ('eventbrite:eb-two-step-lessons', 'a41', false), ('eventbrite:eb-two-step-lessons', 'a43', false), ('eventbrite:eb-two-step-lessons', 'a13', false), ('eventbrite:eb-two-step-lessons', 'a22', false),
  ('attendee:host-tech-meetup-hh', 'a6', false), ('attendee:host-tech-meetup-hh', 'a2', false), ('attendee:host-tech-meetup-hh', 'a7', false), ('attendee:host-tech-meetup-hh', 'a15', false), ('attendee:host-tech-meetup-hh', 'a16', false), ('attendee:host-tech-meetup-hh', 'a17', false), ('attendee:host-tech-meetup-hh', 'a18', false), ('attendee:host-tech-meetup-hh', 'a45', false), ('attendee:host-tech-meetup-hh', 'a46', false), ('attendee:host-tech-meetup-hh', 'a48', false), ('attendee:host-tech-meetup-hh', 'a49', false), ('attendee:host-tech-meetup-hh', 'a50', false), ('attendee:host-tech-meetup-hh', 'a51', false), ('attendee:host-tech-meetup-hh', 'a52', false), ('attendee:host-tech-meetup-hh', 'a53', false), ('attendee:host-tech-meetup-hh', 'a54', false), ('attendee:host-tech-meetup-hh', 'a55', false), ('attendee:host-tech-meetup-hh', 'a56', false), ('attendee:host-tech-meetup-hh', 'a58', false), ('attendee:host-tech-meetup-hh', 'a59', false), ('attendee:host-tech-meetup-hh', 'a60', false), ('attendee:host-tech-meetup-hh', 'a62', false), ('attendee:host-tech-meetup-hh', 'a63', false), ('attendee:host-tech-meetup-hh', 'a9', true),
  ('shotgun:sg-summit-rooftop-dj', 'a3', false), ('shotgun:sg-summit-rooftop-dj', 'a4', false), ('shotgun:sg-summit-rooftop-dj', 'a12', false), ('shotgun:sg-summit-rooftop-dj', 'a19', false), ('shotgun:sg-summit-rooftop-dj', 'a26', false), ('shotgun:sg-summit-rooftop-dj', 'a31', false), ('shotgun:sg-summit-rooftop-dj', 'a56', false), ('shotgun:sg-summit-rooftop-dj', 'a57', false), ('shotgun:sg-summit-rooftop-dj', 'a61', false), ('shotgun:sg-summit-rooftop-dj', 'a45', false), ('shotgun:sg-summit-rooftop-dj', 'a50', false), ('shotgun:sg-summit-rooftop-dj', 'a60', false), ('shotgun:sg-summit-rooftop-dj', 'a63', false), ('shotgun:sg-summit-rooftop-dj', 'a28', false), ('shotgun:sg-summit-rooftop-dj', 'a34', false), ('shotgun:sg-summit-rooftop-dj', 'a40', false), ('shotgun:sg-summit-rooftop-dj', 'a42', false), ('shotgun:sg-summit-rooftop-dj', 'a13', true),
  ('shotgun:sg-rooftop-social', 'a3', false), ('shotgun:sg-rooftop-social', 'a12', false), ('shotgun:sg-rooftop-social', 'a19', false), ('shotgun:sg-rooftop-social', 'a57', false), ('shotgun:sg-rooftop-social', 'a61', false), ('shotgun:sg-rooftop-social', 'a56', false),
  ('shotgun:sg-barbarella-throwback', 'a21', false), ('shotgun:sg-barbarella-throwback', 'a24', false), ('shotgun:sg-barbarella-throwback', 'a28', false), ('shotgun:sg-barbarella-throwback', 'a30', false), ('shotgun:sg-barbarella-throwback', 'a32', false), ('shotgun:sg-barbarella-throwback', 'a36', false), ('shotgun:sg-barbarella-throwback', 'a38', false), ('shotgun:sg-barbarella-throwback', 'a40', false), ('shotgun:sg-barbarella-throwback', 'a44', false), ('shotgun:sg-barbarella-throwback', 'a49', false), ('shotgun:sg-barbarella-throwback', 'a51', false), ('shotgun:sg-barbarella-throwback', 'a55', false),
  ('shotgun:sg-open-air-block-party', 'a2', false), ('shotgun:sg-open-air-block-party', 'a6', false), ('shotgun:sg-open-air-block-party', 'a16', false), ('shotgun:sg-open-air-block-party', 'a45', false), ('shotgun:sg-open-air-block-party', 'a46', false), ('shotgun:sg-open-air-block-party', 'a48', false), ('shotgun:sg-open-air-block-party', 'a50', false), ('shotgun:sg-open-air-block-party', 'a51', false), ('shotgun:sg-open-air-block-party', 'a53', false), ('shotgun:sg-open-air-block-party', 'a55', false), ('shotgun:sg-open-air-block-party', 'a58', false), ('shotgun:sg-open-air-block-party', 'a59', false), ('shotgun:sg-open-air-block-party', 'a60', false), ('shotgun:sg-open-air-block-party', 'a62', false), ('shotgun:sg-open-air-block-party', 'a63', false), ('shotgun:sg-open-air-block-party', 'a19', false), ('shotgun:sg-open-air-block-party', 'a22', false), ('shotgun:sg-open-air-block-party', 'a26', false), ('shotgun:sg-open-air-block-party', 'a31', false), ('shotgun:sg-open-air-block-party', 'a34', false), ('shotgun:sg-open-air-block-party', 'a36', false), ('shotgun:sg-open-air-block-party', 'a42', false), ('shotgun:sg-open-air-block-party', 'a9', true),
  ('partiful:ptf-wine-on-second', 'a3', false), ('partiful:ptf-wine-on-second', 'a4', false), ('partiful:ptf-wine-on-second', 'a5', false), ('partiful:ptf-wine-on-second', 'a8', false), ('partiful:ptf-wine-on-second', 'a11', false), ('partiful:ptf-wine-on-second', 'a14', false), ('partiful:ptf-wine-on-second', 'a57', false), ('partiful:ptf-wine-on-second', 'a61', false),
  ('partiful:ptf-zilker-picnic', 'a19', false), ('partiful:ptf-zilker-picnic', 'a8', false), ('partiful:ptf-zilker-picnic', 'a12', false), ('partiful:ptf-zilker-picnic', 'a26', false), ('partiful:ptf-zilker-picnic', 'a56', false), ('partiful:ptf-zilker-picnic', 'a61', false), ('partiful:ptf-zilker-picnic', 'a48', false), ('partiful:ptf-zilker-picnic', 'a63', false),
  ('partiful:ptf-late-night-pizza', 'a45', false), ('partiful:ptf-late-night-pizza', 'a50', false), ('partiful:ptf-late-night-pizza', 'a52', false), ('partiful:ptf-late-night-pizza', 'a55', false), ('partiful:ptf-late-night-pizza', 'a58', false), ('partiful:ptf-late-night-pizza', 'a60', false), ('partiful:ptf-late-night-pizza', 'a62', false), ('partiful:ptf-late-night-pizza', 'a63', false), ('partiful:ptf-late-night-pizza', 'a21', false), ('partiful:ptf-late-night-pizza', 'a32', false), ('partiful:ptf-late-night-pizza', 'a38', false), ('partiful:ptf-late-night-pizza', 'a13', false), ('partiful:ptf-late-night-pizza', 'a9', true),
  ('luma:luma-stripe-payments-eng', 'a1', false), ('luma:luma-stripe-payments-eng', 'a5', false), ('luma:luma-stripe-payments-eng', 'a8', false), ('luma:luma-stripe-payments-eng', 'a14', false), ('luma:luma-stripe-payments-eng', 'a15', false), ('luma:luma-stripe-payments-eng', 'a17', false), ('luma:luma-stripe-payments-eng', 'a20', false), ('luma:luma-stripe-payments-eng', 'a23', false), ('luma:luma-stripe-payments-eng', 'a39', false), ('luma:luma-stripe-payments-eng', 'a11', false),
  ('luma:luma-nvidia-inference', 'a2', false), ('luma:luma-nvidia-inference', 'a45', false), ('luma:luma-nvidia-inference', 'a50', false), ('luma:luma-nvidia-inference', 'a52', false), ('luma:luma-nvidia-inference', 'a54', false), ('luma:luma-nvidia-inference', 'a58', false), ('luma:luma-nvidia-inference', 'a60', false), ('luma:luma-nvidia-inference', 'a62', false), ('luma:luma-nvidia-inference', 'a16', false), ('luma:luma-nvidia-inference', 'a53', false),
  ('luma:luma-datadog-observability', 'a6', false), ('luma:luma-datadog-observability', 'a7', false), ('luma:luma-datadog-observability', 'a18', false), ('luma:luma-datadog-observability', 'a46', false), ('luma:luma-datadog-observability', 'a48', false), ('luma:luma-datadog-observability', 'a49', false), ('luma:luma-datadog-observability', 'a51', false), ('luma:luma-datadog-observability', 'a55', false), ('luma:luma-datadog-observability', 'a59', false),
  ('luma:luma-github-open-source', 'a2', false), ('luma:luma-github-open-source', 'a45', false), ('luma:luma-github-open-source', 'a46', false), ('luma:luma-github-open-source', 'a50', false), ('luma:luma-github-open-source', 'a51', false), ('luma:luma-github-open-source', 'a53', false), ('luma:luma-github-open-source', 'a58', false), ('luma:luma-github-open-source', 'a60', false), ('luma:luma-github-open-source', 'a62', false), ('luma:luma-github-open-source', 'a63', false), ('luma:luma-github-open-source', 'a55', false);
